const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
const REQUEST_GIF_PENDING = 'REQUEST_GIF_PENDING';
const REQUEST_GIF_SUCCESS = 'REQUEST_GIF_SUCCESS';
const REQUEST_GIF_FAILED  = 'REQUEST_GIF_FAILED';
const CLEAR_GIFS_LIST     = 'CLEAR_GIFS_LIST';

export {
    CHANGE_SEARCH_FIELD,
    REQUEST_GIF_PENDING,
    REQUEST_GIF_SUCCESS,
    REQUEST_GIF_FAILED,
    CLEAR_GIFS_LIST
}


