const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
const REQUEST_GIF_PENDING = 'REQUEST_GIF_PENDING';
const REQUEST_GIF_SUCCESS = 'REQUEST_GIF_SUCCESS';
const REQUEST_GIF_FAILED  = 'REQUEST_GIF_FAILED';

export {
    CHANGE_SEARCH_FIELD,
    REQUEST_GIF_PENDING,
    REQUEST_GIF_SUCCESS,
    REQUEST_GIF_FAILED
}


